### ISSUE TITLE
Results not appearing on Google, Toggle not being correctly set.

### ISSUE THREAD

**Issue by sammorrisdesign** [the-markup/tool-simple-search#17]
I haven't had time to fully diagnose what's happening here. But in both Chrome and Firefox, Google results are not being cleaned up and displayed. This is with a fresh install of the extension. A few people have left reviews on the Chrome store stating it doesn't work for them either.

A good starting place would be the `toggle`. It appears it's not being set correctly as I'm seeing `initial load: toggle off` in the console for both Google and Bing searches. Which would explain why it's not running on Google (but why is it displaying on Bing without the toggle???)

dumpsterfire.jpg

**Comment by varner** [comment]
Updated parsers to solve this issue.
