### ISSUE TITLE
Bug: "coronavirus" query on google returns blank screen

### ISSUE THREAD

**Issue by varner** [the-markup/tool-simple-search#5]

**Comment by sammorrisdesign** [comment]
I'm also seeing this on searches for album pages.

Example: https://www.google.com/search?sxsrf=ALeKk01VIOBHhjyMqPFSD0sklvy8BUoDUg%3A1605634296402&ei=-Ai0X-iTGKWk_Qakw6Z4&q=open+mike+eagle+anime+trauma+and+divorce&gs_ssp=eJzj4tVP1zc0zC4vSYu3LCo3YPTSyC9IzVPIzcxOVUhNTM9JVUjMy8xNVSgpSizNTQRyUhRSMsvyi5JTASoyE-g&oq=open+mike&gs_lcp=CgZwc3ktYWIQAxgDMgQIIxAnMggILhCxAxCRAjIFCAAQkQIyAgguMgIIADICCC4yAggAMgQIABBDMgIIADICCAA6GgguELADEIoDELcDEOUCEIsDEJgDEKgDEJMCOhcILhCwAxCKAxC3AxDlAhCLAxCYAxCoAzoRCAAQsAMQigMQtwMQ5QIQiwM6DgguELADEIsDEJgDEKgDOgUILhCRAjoLCC4QsQMQxwEQowI6BQgAELEDOggIABCxAxCDAToICC4QsQMQgwE6BAguEENQgbMFWLa5BWDTxgVoAnAAeAGAAZYCiAGnCZIBBTQuNC4xmAEAoAEBqgEHZ3dzLXdpesgBCbgBAsABAQ&sclient=psy-ab

**Comment by varner** [comment]
Now fails gracefully.
