### ISSUE TITLE
"Did you mean" text disappears upon closing simple results

### ISSUE THREAD

**Issue by dphiffer** [the-markup/tool-simple-search#7]
<img width="1026" alt="Screen Shot 2020-11-16 at 4 45 22 PM" src="https://user-images.githubusercontent.com/38114/99311840-31d9e380-282b-11eb-8c69-deaab95f4a0c.png">

Seems like the "did you mean" text should stay here:

<img width="1172" alt="Screen Shot 2020-11-16 at 4 45 32 PM" src="https://user-images.githubusercontent.com/38114/99311852-356d6a80-282b-11eb-8259-7efae5a105f6.png">

**Comment by dphiffer** [comment]
On the other hand, maybe the repetition of the "did you mean" text would be too jarring?

**Comment by gtnuux** [comment]
This seems to just be a typo.  On lines 117--120 of content.js:
```javascript
if (didYouMean) {
  const clonedDidYouMean = didYouMean.cloneNode(true);
  results.prepend(didYouMean);
}
```
I think the last line should be:
`  results.prepend(clonedDidYouMean);`

Pre-pending `didYouMean` removes it from the base page.
-Jeff
